spring.application.name=tiffino_main
# ===============================
# Server Config
# ===============================
server.port=8080

# ===============================
# Database Config (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/tiffinotask?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / Hibernate Config
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT Secret Key & Expiration
# ===============================
jwt.secret=MySuperSecretKeyForJWT123456789
jwt.expiration=3600000

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=asmitag9232@gmail.com
spring.mail.password=hilg bfqc veiz radv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cloudinary
cloudinary.cloud_name=dicw4txvl
cloudinary.api_key=278323264417252
cloudinary.api_secret=sp7ykXGQeUIfkw2ibz01yO6gjVo


spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# use a single sensible path for Swagger UI
# either remove this property entirely to use defaults,
# or set it explicitly to /swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html


# ? Static Resource Config (for chatbot frontend)
spring.web.resources.static-locations=classpath:/static/
 






